name: Build Flutter App

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.24.1'

    - name: Install project dependencies
      run: flutter config --no-analytics && flutter pub get

    - name: Enable windows build
      run: flutter config --enable-windows-desktop

    - name: Build artifacts
      run: flutter build windows --release

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WorklogAssistant-windows-${{ github.run_number}}
        path: build/windows/x64/runner/Release

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/windows/x64/runner/Release/*
        token: ${{ secrets.GITHUB_TOKEN }}
        name: "Release ${{ github.ref }}"